version: '2'

services:
  postgres:
    image: postgres:10
    env_file: .env
    environment:
      POSTGRES_USER: $POSTGRES_USER
      POSTGRES_DB: $POSTGRES_DB
      POSTGRES_PASSWORD: $POSTGRES_PASSWORD
      PGDATA: $PGDATA
    volumes:
       - /dbdata/:$PGDATA
    ports:
      - "5432:5432"
    restart: always

  app:
    env_file: .env
    build:
      context: .
      args:
        SQLALCHEMY_DATABASE_URI: $SQLALCHEMY_DATABASE_URI
        ENV: $ENV
        TESTING: $TESTING
        DEBUG: $DEBUG
    ports:
      - "5000:5000"
    depends_on:
      - postgres
    restart: always

  web:
    image: nginx
    env_file: .env
    ports:
      - "443:443"
    volumes:
      - /var/html/www/:/app
      - /etc/ssl/englishsubs/englishsubs.ru.crt:/etc/ssl/englishsubs/englishsubs.ru.crt
      - /etc/ssl/englishsubs/englishsubs.ru.key:/etc/ssl/englishsubs/englishsubs.ru.key
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
    restart: always