version: '2'

services:
  postgres:
    image: postgres
    env_file: .env
    environment:
      POSTGRES_USER: $POSTGRES_USER
      POSTGRES_DB: $POSTGRES_DB
      POSTGRES_PASSWORD: $POSTGRES_PASSWORD
      PGDATA: $PGDATA
    volumes:
       - /dbdata/:$PGDATA
    ports:
      - "5432:5432"
    restart: always

  pgadmin:
    image: dpage/pgadmin4
    env_file: .env
    environment:
      PGADMIN_DEFAULT_EMAIL: $PGADMIN_DEFAULT_EMAIL
      PGADMIN_DEFAULT_PASSWORD: $PGADMIN_DEFAULT_PASSWORD
    volumes:
       - /pgadmin:/var/lib/pgadmin
    ports:
      - "5050:80"
    restart: always

  app:
    env_file: .env
    build:
      context: .
      args:
        SQLALCHEMY_DATABASE_URI: $SQLALCHEMY_DATABASE_URI
        ENV: $ENV
        TESTING: $TESTING
        DEBUG: $DEBUG
    ports:
      - "5000:5000"
    depends_on:
      - postgres
    volumes:
      - .:/app
    restart: always

