"""empty message

Revision ID: 4a473a587a0d
Revises: 7b299b4b5121
Create Date: 2018-07-10 01:55:38.259672

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4a473a587a0d'
down_revision = '7b299b4b5121'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('serial', sa.Column('description', sa.Text()))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('serial', 'description')
    # ### end Alembic commands ###
