"""empty message

Revision ID: 729550b43d28
Revises: b48129198c06
Create Date: 2018-10-14 00:56:38.240003

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '729550b43d28'
down_revision = 'b48129198c06'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('episode', 'videoSrc')
    op.drop_column('episode', 'subtitleSrc')
    op.drop_column('episode', 'previewImageSrc')
    op.add_column('serial', sa.Column('static_dirname', sa.String(length=120), nullable=True))
    op.drop_column('serial', 'posterSrc')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('serial', sa.Column('posterSrc', sa.VARCHAR(length=120), autoincrement=False, nullable=True))
    op.drop_column('serial', 'static_dirname')
    op.add_column('episode', sa.Column('previewImageSrc', sa.VARCHAR(length=120), autoincrement=False, nullable=True))
    op.add_column('episode', sa.Column('subtitleSrc', sa.VARCHAR(length=120), autoincrement=False, nullable=False))
    op.add_column('episode', sa.Column('videoSrc', sa.VARCHAR(length=120), autoincrement=False, nullable=False))
    # ### end Alembic commands ###
