"""empty message

Revision ID: b48129198c06
Revises: 4a473a587a0d
Create Date: 2018-10-14 00:05:00.473515

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b48129198c06'
down_revision = '4a473a587a0d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('serial', sa.Column('posterSrc', sa.String(length=120), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('serial', 'posterSrc')
    # ### end Alembic commands ###
