"""empty message

Revision ID: e49635072b72
Revises: 8de8cb91cfaf
Create Date: 2018-06-19 23:17:00.480466

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e49635072b72'
down_revision = '8de8cb91cfaf'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('serial', sa.Column('previewImageSrc', sa.String(length=120)))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('serial', 'previewImageSrc')
    # ### end Alembic commands ###
